# pull official base image
FROM python:3.10-alpine

RUN mkdir /usr/src/staticfiles
RUN mkdir /usr/src/djangoProject

# set work directory
WORKDIR /usr/src/djangoProject

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r ./requirements.txt


# copy project
COPY . .

CMD ['python', 'manage.py', 'collectstatic', '--noinput']