# Generated by Django 4.1.2 on 2022-11-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interruptcheckwordknow',
            name='NameText',
            field=models.CharField(default='_', max_length=255, verbose_name='Название текста'),
        ),
    ]
