# Generated by Django 4.1.2 on 2022-11-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_interruptcheckwordknow_nametext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interruptcheckwordknow',
            name='UserID_WorldOwner',
            field=models.CharField(default='_', max_length=255, verbose_name='Пользователь'),
        ),
    ]
