# Generated by Django 4.1.3 on 2022-11-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_words_userid_worldowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordGeneralKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EngWord', models.CharField(max_length=255, verbose_name='Английское знакомое слово')),
            ],
            options={
                'verbose_name': 'Знакомые всем слова',
                'verbose_name_plural': 'Знакомые всем слова',
                'ordering': ['id'],
            },
        ),
    ]
