# Generated by Django 4.1.3 on 2022-12-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_wordgeneralknow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='time_create',
        ),
    ]
