# Generated by Django 4.1.3 on 2022-12-07 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_words_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
