# Generated by Django 4.1.3 on 2022-12-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_words_time_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordGeneralStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default='_', max_length=255, verbose_name='Имя пользователя')),
                ('CountErrLastTry', models.IntegerField(default='0', verbose_name='Кол-во ошибок в прошлый раз')),
                ('StartLearn', models.IntegerField(default='0', verbose_name='Уроков начато')),
                ('LearnComplete', models.IntegerField(default='0', verbose_name='Уроков закончено')),
            ],
            options={
                'verbose_name': 'Общая статистика',
                'verbose_name_plural': 'Общая статистика',
                'ordering': ['id'],
            },
        ),
    ]
